easy_admin:
    design:
        brand_color: '#337ab7'
        assets:
            css:
              - /bundles/app/css/style.css
        menu:
          - { entity: 'User', icon: 'user', role: ROLE_ADMIN }
          - { entity: 'Page', icon: 'file', role: ROLE_ADMIN }
          - { entity: 'UserLog', icon: 'database', role: ROLE_ADMIN }