easy_admin:
    entities:
        UserLog:
            class: AppBundle\Entity\UserLog
            label: admin.link.user_log
            role: ROLE_USER
            show:
                role: ROLE_ADMIN
                actions: ['list', '-edit', '-delete']
            list:
                actions: ['show', '-edit', '-delete']
