services:

  app.subscriber:
    class: AppBundle\EventListener\AppSubscriber
    arguments:
        - "@service_container"
    tags:
        - { name: kernel.event_subscriber }

  app.locale.listener:
    class: AppBundle\EventListener\LocaleListener
    arguments:
      - "%kernel.default_locale%"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 17 }
