admin:
  resource: "@AppBundle/Controller/AdminController.php"
  type:     annotation

locale:
  resource: "@AppBundle/Controller/LocaleController.php"
  type:     annotation

bpeh_page_reorder:
  path: /admin/reorder
  defaults:
    _controller: BpehNestablePageBundle:Page:reorder

# FOS user bundle default routing
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

frontend:
  resource: "@AppBundle/Controller/FrontendController.php"
  type:     annotation

easy_admin_bundle:
  resource: "@AppBundle/Controller/AdminController.php"
  type:     annotation
  prefix:   /%admin_path%